# Generated by Django 5.1.5 on 2026-01-23 01:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frete'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lucro'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Imposto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Total'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Unitário'),
        ),
    ]
