# Generated by Django 5.1.5 on 2026-01-23 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_saleitem_freight_saleitem_profit_saleitem_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncost',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Indica se este custo foi usado em uma venda liquidada', verbose_name='Travado'),
        ),
        migrations.AddField(
            model_name='productioncost',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Travado em'),
        ),
        migrations.AddField(
            model_name='productioncost',
            name='locked_by_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_costs', to='inventory.sale', verbose_name='Venda que Travou'),
        ),
        migrations.AddField(
            model_name='productioncost',
            name='refinement_code',
            field=models.CharField(blank=True, help_text='Código único que agrupa custos do mesmo refinamento', max_length=50, null=True, verbose_name='Código de Refinamento'),
        ),
        migrations.AddField(
            model_name='productioncost',
            name='refinement_name',
            field=models.CharField(blank=True, help_text='Nome descritivo do refinamento', max_length=200, null=True, verbose_name='Nome do Refinamento'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Custo Calculado em'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_refinement_code',
            field=models.CharField(blank=True, help_text='Código do refinamento de custo usado neste item', max_length=50, null=True, verbose_name='Código de Refinamento de Custo'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_snapshot',
            field=models.JSONField(blank=True, help_text='Detalhamento dos custos no momento da venda', null=True, verbose_name='Snapshot do Custo'),
        ),
        migrations.AlterField(
            model_name='productioncost',
            name='cost_type',
            field=models.CharField(choices=[('aviamentos', 'Aviamentos'), ('corte_tecido', 'Corte do tecido'), ('costura', 'Costura'), ('dtf', 'DTF'), ('embalagem', 'Embalagem'), ('etiqueta', 'Etiqueta'), ('silk', 'Silk'), ('sublimacao', 'Sublimação'), ('tipo_tecido', 'Tipo de tecido')], max_length=20, verbose_name='Tipo de Custo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('disputa', 'Disputa'), ('homologado', 'Homologado'), ('producao', 'Produção'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('liquidado', 'Liquidado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='productioncost',
            index=models.Index(fields=['refinement_code'], name='inventory_p_refinem_b261bb_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncost',
            index=models.Index(fields=['is_locked'], name='inventory_p_is_lock_ec89f7_idx'),
        ),
    ]
