# Generated by Django 5.1.5 on 2026-01-24 00:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productioncost_is_locked_productioncost_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='nf',
            field=models.CharField(blank=True, help_text='Número da Nota Fiscal', max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de imposto aplicado sobre o valor total', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual de Imposto (%)'),
        ),
    ]
