# Generated by Django 5.1.5 on 2026-01-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sale_nf_sale_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('venda', 'Venda'), ('dispensa', 'Dispensa'), ('pregao', 'Pregão')], default='venda', max_length=20, verbose_name='Tipo de Venda'),
        ),
    ]
