# Generated by Django 5.1.5 on 2026-01-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sale_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
