# Generated by Django 5.1.5 on 2026-01-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='productioncost',
            name='cost_type',
            field=models.CharField(max_length=50, verbose_name='Tipo de Custo'),
        ),
        migrations.AlterField(
            model_name='productioncost',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
