# Generated by Django 5.1.5 on 2026-01-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_customer_neighborhood_customer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
    ]
