# Generated by Django 5.1.5 on 2026-02-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='inscricao_municipal',
        ),
        migrations.AddField(
            model_name='productioncost',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_costs', to='inventory.customer', verbose_name='Cliente'),
        ),
    ]
