# Generated by Django 5.1.5 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_company_inscricao_municipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('disputa', 'Disputa'), ('aguardando_julgamento', 'Aguardando Julgamento'), ('homologado', 'Homologado'), ('em_producao', 'Em Produção'), ('em_transito', 'Em Trânsito'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('liquidado', 'Liquidado')], default='disputa', max_length=30, verbose_name='Status'),
        ),
    ]
