# Generated by Django 5.1.5 on 2026-04-08 22:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_company_inscricao_municipal_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncost',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade da venda vinculada a este custo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantidade'),
        ),
    ]
