# Generated by Django 5.1.5 on 2026-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_quantity_to_production_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncost',
            name='cost_category',
            field=models.CharField(choices=[('sale', 'Custo de Venda'), ('production', 'Custo de Produção')], default='sale', help_text='sale = vinculado a venda; production = entrada de estoque/produção', max_length=20, verbose_name='Categoria'),
        ),
    ]
