# Generated by Django 5.1.5 on 2026-09-14 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_cost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Venda'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('entregue', 'Entregue')], default='pendente', max_length=20, verbose_name='Status do Item'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('venda', 'Venda'), ('dispensa', 'Dispensa'), ('pregao', 'Pregão'), ('uniforme', 'Venda - Uniforme')], default='venda', max_length=20, verbose_name='Tipo de Venda'),
        ),
    ]
