# Generated by Django 5.1.5 on 2026-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_discount',
            field=models.IntegerField(default=0, verbose_name='Desconto Máximo (%)'),
        ),
    ]
